### ISSUE TITLE
Please, update the package in pypi.python.org.

### ISSUE THREAD

**Issue by khajvahmac** [jsocol/django-pymemcache#6]
The `basestring` issue is still present in the package in pypi.python.org, if we are using python3. Please, update the package there, so others can install this with pip.

**Comment by ameswarb** [comment]
:+1:

**Comment by adambullmer** [comment]
:+1:

**Comment by jsocol** [comment]
I never actually ended up using this library. Does anyone want to maintain it on PyPI? I'll push the repo over to you and give you access if you let me know your pypi username.

**Comment by adambullmer** [comment]
Not sure about how the release process works on pypi, but I think you might need to just tag the current master branch with the next version

**Comment by jsocol** [comment]
It's more complicated than that, but it's not just a question of "updating it on PyPI" but of maintaining a library I never ended up using once I started it. There's time that goes into

* triaging and reviewing pull requests,
* triaging and helping with issues,
* fixing bugs (either from issues or that you notice yourself),
* keeping the test suite up-to-date with new Django and pymemcache versions
* (_writing_ a test suite in the first place, which I never did because I went another way),
* figuring out when versions should change and by how much,
* maintaining changelogs,
* and then actually updating it (which is [slightly more complicated](https://docs.python.org/2/distutils/packageindex.html#package-index), but not very).

I maintain a lot of libraries. I've been trying to cut back and find new maintainers because I don't have time. I do not have time to maintain this one--frankly I'd forgotten about this one. I'm happy to give the keys to a new maintainer.

**Comment by khajvahmac** [comment]
@jsocol I am using this library right now and I find it useful. I don't have experience in maintaining libraries but I would be glad to try.

**Comment by jsocol** [comment]
@khajvahmac do you have a username on [pypi](https://pypi.python.org/pypi)?

**Comment by khajvahmac** [comment]
@jsocol I have just created an account. My username is: khajvah

**Comment by jsocol** [comment]
@khajvahmac Thanks! Added you to the PyPI package, now going to see about pushing the repo over to you.

**Comment by jsocol** [comment]
Transfer started, but I think you'll have to accept / approve it.

**Comment by khajvahmac** [comment]
@jsocol Ops, I think, it expired. Sorry about that, can you transfer it again?

**Comment by jsocol** [comment]
@khajvahmac Restarted. It said it was still pending, so I aborted and tried again
